name: Feature request
description: Suggest an idea
title: "[FEAT] "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the solution you'd like
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ]
        - [ ]
